spring:
  datasource:
    url: jdbc:mysql://camping-app-backend-database.cjorih4jsles.ap-northeast-2.rds.amazonaws.com:3306/camping
    username: root
    password: ehdgml1!2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        sql_show: true
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
  logging:
    level:
      org:
        hibernate:
          SQL: debug
          type:
            descriptor:
              sql: trace
      #  logging:
      #    level:
      #      org.hibernate.SQL: debug
      # org.hibernate.type: trace
